### ISSUE TITLE
SOAP FAIL: TypeError: name.toUpperCase is not a function

### ISSUE THREAD

**Issue by gitnan** [circa10a/easy-soap-request#11]
Hi,

I get the following error thrown when trying to sent the SOAP request:

SOAP FAIL: TypeError: name.toUpperCase is not a function
(node:4352) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: name.toUpperCase is not a function
(node:4352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Could you please advise?

**Comment by circa10a** [comment]
Can you send me an snippet of your usage with any sensitive data scrubbed?

**Comment by gitnan** [comment]
Please see below:

![image](https://user-images.githubusercontent.com/13163756/51735459-66414600-207f-11e9-88f2-b7e81e3b917a.png)

**Comment by gitnan** [comment]
I have managed to resolve this issue now, the issue was that the:

`const url = 'https://url.com`

was outside of the `ipc.Main.on` 

Thank you for your assistance on this
