### ISSUE TITLE
Add header options in result

### ISSUE THREAD

**Issue by Kein-Wai** [circa10a/easy-soap-request#12]
Hello There,

Could you please add the header options in your return for your next release?

something like this

module.exports = function soapRequest(url, headers, xml, timeout = 10000) {
  return new Promise((resolve, reject) => {
    axios({
      method: 'post',
      url,
      headers,
      data: xml,
      timeout,
    }).then((response) => {
      resolve({
        response: {
          body: response.data,
          statusCode: response.status,
          headers: response.headers,
        },
      });
    }).catch((error) => {
      if (error.response) {
        console.error(`SOAP FAIL: ${error}`);
        reject(error.response.data);
      } else {
        console.error(`SOAP FAIL: ${error}`);
        reject(error);
      }
    });
  });
};

**Comment by circa10a** [comment]
@Kein-Wai That's a good idea and wouldn't introduce a breaking change. I might not get to it for a couple of days. If you want to make a PR, i'm good with it.

**Comment by Kein-Wai** [comment]
Thanks,

I would love to, but I do not have permission to push any new branches to the repository :-(

**Comment by circa10a** [comment]
You can fork the repository and then make a PR back to the original easy-soap-request repo(this one)

**Comment by circa10a** [comment]
Fixed with #13
