### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by seand52** [circa10a/easy-soap-request#15]
Hi,

In the documentation there is no reference to how to go about making a request with basic authentication (username, password, domain). I'm assuming I have to put the credentials in the user-agent? Is there a somewhere I can see where this is done for reference?

Thanks

**Comment by circa10a** [comment]
You can perform basic auth by using an `Authorization` header using base64 encoded credentials like so:

```js
const soapRequest = require('easy-soap-request');
const fs = require('fs');

// example data
const url = 'https://something';
const headers = {
  'user-agent': 'sampleTest',
  'Content-Type': 'text/xml;charset=UTF-8',
  'soapAction': 'something',
  'Authorization': 'Basic bXlVc2VyOm15UGFzc3dvcmQK'
};
const xml = fs.readFileSync('test/zipCodeEnvelope.xml', 'utf-8');

// usage of module
(async () => {
  const { response } = await soapRequest(url, headers, xml, 1000); // Optional timeout parameter(milliseconds)
  const { headers, body, statusCode } = response;
  console.log(headers);
  console.log(body);
  console.log(statusCode);
})();
```

To encode your credentials as base64:

```sh
❯ echo "myUser:myPassword" | base64
bXlVc2VyOm15UGFzc3dvcmQK
```

**Comment by seand52** [comment]
Hi, I have one more question. Does this support ntlm authentication? I'm trying to access a Navision Web service and it seems like ntlm is required when accessing from Node
