### ISSUE TITLE
add proxy option in request

### ISSUE THREAD

**Issue by razone** [circa10a/easy-soap-request#16]

**Comment by razone** [comment]
We need to add proxy option in the request since axios already supports this. So request will be

soapRequest(url, headers, xml, timeout = 10000, proxy = false)

and then proxy variable will be included in the axios request like this

  axios({
      method: 'post',
      url,
      headers,
      data: xml,
      timeout,
      proxy,
    })

**Comment by circa10a** [comment]
Fixed in #17
we be pushed with `2.5.0`
