### ISSUE TITLE
making request with pfx certificate

### ISSUE THREAD

**Issue by grega913** [circa10a/easy-soap-request#2]
Hello - - I started using this module for SOAP requests and manged to make it work with basic authentication. However, now I have the situation where authentication should be made via pfx certificate.
I am stuck as don't know where to put the cert path and how to make it work??
If someone can please be so kind and describe the way - - I am using the async version:
`try {
    const { response } = await soapRequest(url, headers, xml_getTemperatures);
    const { body, statusCode } = response;
.
.
.`

Thank you a lot.

**Comment by circa10a** [comment]
@grega913 We'll need to add an optional parameter for pfx and modify the agent if pfx is present
See:
https://github.com/axios/axios/issues/1304

**Comment by grega913** [comment]
I am open to anything - - just need this to work - - whad do you want me to do?

**Comment by grega913** [comment]
I got this to work with plain axios - -with your help - - -thank you a lot man:

`const axios = require("axios");
const fs = require("fs");
const https = require("https");
const { createXmlForGetTemperaturesForAllAreas } = require("./temp_helperz.js");
var url = "<https://yourwsdlservice?wsdl>";


const agent = new https.Agent({
  rejectUnauthorized: false,
  strictSSL: false,
  pfx: fs.readFileSync(__dirname + "</yourcertificate.pfx>"),
  passphrase: "<password>"
});

//this function creates envelope xmp string
var xml3 = createXmlForGetTemperaturesForAllAreas(
  "1",
  "2018-01-01T00:00:00Z",
  "2018-02-01T00:00:00Z"
);

const getAllZonesData = async () => {
  try {
    let res = await axios({
      url: url,
      method: "post",
      httpsAgent: agent,
      data: xml3,
      headers: {
        "Content-Type": "text/xml;charset=utf-8",
        SOAPAction:
          "<http://yoursoapaction>"
      }
    });
    if (res.status == 200) {
      // test for status you want, etc
      console.log(res.data);
    }
    // Don't forget to return something
    return res.data;
  } catch (err) {
    console.error(err);
  }
};

getAllZonesData();
`
