### ISSUE TITLE
Error SOAP FAIL

### ISSUE THREAD

**Issue by lfcoelho1** [circa10a/easy-soap-request#24]
Hi, we use Easy Soap Request to send XML File Details to our Service.
But when the file was bigger than 12 MB, generate this error attached.

<img width="369" alt="Captura de Tela 2019-09-30 às 15 16 16" src="https://user-images.githubusercontent.com/29629143/65905069-38429d00-e396-11e9-8ad8-e4354fba994a.png">

**Comment by circa10a** [comment]
Have you tried increasing the default timeout?

**Comment by lfcoelho1** [comment]
> Have you tried increasing the default timeout?

Yes, i increase!

 await soapRequest(url, headers, xml, 30000).catch(err => {throw new Error(err)});

But do not work!

**Comment by circa10a** [comment]
Can you try:

```javascript
await soapRequest(url, headers, xml, timeout=30000).catch(err => {throw new Error(err)});
```

**Comment by circa10a** [comment]
@lfcoelho1 

easy-soap-request was just updated to `3.0.0`

This was a breaking change, hence the major version update. If you install the new version you would now do:

```javascript
await soapRequest({ url, headers, xml, timeout: 30000 }).catch(err => {throw new Error(err)});
```

**Comment by circa10a** [comment]
No response, but this issue is just related to how you're passing the timeout setting, bit with `easy-soap-request`
