### ISSUE TITLE
The module is not working

### ISSUE THREAD

**Issue by thedevelopervishal** [circa10a/easy-soap-request#31]
The module is throwing with an error as follows:

(node:14948) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `response` of 'undefined' or 'null'.
    at C:\Users\Musk_Jr\Desktop\VINKTECK\soap\index.js:26:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:14948) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

**Comment by circa10a** [comment]
@thedevelopervishal can you show how you're using the module and mask any sensitive data?

**Comment by circa10a** [comment]
@thedevelopervishal any updates?

**Comment by Elyx0** [comment]
I think 3.2.0 broke something, It tells me `SOAP FAIL: TypeError: Parameter "url" must be a string, not undefined` 2.6 was ok

**Comment by circa10a** [comment]
@Elyx0 can you show how you're using it?

**Comment by Elyx0** [comment]
I was using it with arguments separated by commas but it seems it's now expecting an object
```
-      data = await soapRequest(url, headers, xmlEnvelop);
+      data = await soapRequest({ url, headers, xmlEnvelop });
```
Is there typescript typings for this module?

**Comment by circa10a** [comment]
@Elyx0 There aren't any type bindings.

In [3.0](https://github.com/circa10a/easy-soap-request/releases/tag/3.0.0) there was the switch to use an object as the only parameter. Also published in the [changelog](https://github.com/circa10a/easy-soap-request/blob/master/CHANGELOG.md). I did my best to update all the references and docs to publicize the change.

**Comment by circa10a** [comment]
For existing code, npm should not upgrade your dependencies by a major version to keep things working unless you explicitly tell npm to do so.

**Comment by Elyx0** [comment]
Yeah I wish there was an easy way to get the changelog when you npm update, i feel the error was misleading since I thought my `url` parameter was suddenly empty. You could check that `opts` is an object

**Comment by circa10a** [comment]
@Elyx0 I'm open to PR's ;)
