### ISSUE TITLE
WSSecurity

### ISSUE THREAD

**Issue by AnthonyLzq** [circa10a/easy-soap-request#34]
Hi, I was reading the documentation and I couldn't find a way to do a WSS authentication (with username and password), is there a way to do that? 

Something like: 
```node
const wsSecurity = new WSSecurity(username, password, options)
client.setSecurity(wsSecurity)
```

**Comment by circa10a** [comment]
WS-Security is just a part of the SOAP payload.

[Example](https://docs.servicenow.com/bundle/orlando-application-development/page/integrate/inbound-soap/reference/r_SmplWSSecSOAPEnvHeader.html)

So you would just build out the XML in your application with the appropriate parameters and pass that via the `xml` field like in the provided examples in the readme.

**Comment by AnthonyLzq** [comment]
So, there is not a way to send some parameters using a ```json``` template? I mean, instead of building an ```xml``` by my own.

Maybe, as follows:
```node
const url = 'https://graphical.weather.gov/xml/SOAP_server/ndfdXMLserver.php'
const sampleHeaders = {
  'user-agent': 'sampleTest',
  'Content-Type': 'text/xml;charset=UTF-8',
  'soapAction': 'https://graphical.weather.gov/xml/DWMLgen/wsdl/ndfdXML.wsdl#LatLonListZipCode',
  'SecurityType': 'WSS'
  'Username': 'my_user_name',
  'Pasword': 'my_password',
}
const xml = fs.readFileSync('test/zipCodeEnvelope.xml', 'utf-8')
(async () => {
  const { response } = await soapRequest({ url: url, headers: sampleHeaders, xml: xml, timeout: 1000 }); // Optional timeout parameter(milliseconds)
  const { headers, body, statusCode } = response
  console.log(headers)
  console.log(body)
  console.log(statusCode)
})()
```

**Comment by circa10a** [comment]
That should work. Have you tried it yet?

**Comment by AnthonyLzq** [comment]
I haven't, but I will!

**Comment by circa10a** [comment]
@AnthonyLzq Let me know if does/doesn't work for you. If it does, we can close the issue.
