### ISSUE TITLE
Tests soap - negative case

### ISSUE THREAD

**Issue by malpaclick** [circa10a/easy-soap-request#44]
I use easy-soap-request with jestjs.io and I would like to test a negative case. If the request fails, the test reports a failed test. 
Failed: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\">...
Can you make the test go green with a negative case?

**Comment by circa10a** [comment]
I'm doing a similar thing [here](https://github.com/circa10a/easy-soap-request/blob/master/test/retrieve-lng-lat-test.js#L32-L45)

Here's an pseudocode example:

```javascript
test('Should catch connection error Promise Rejection', async () => {
       expect(await soapRequest({
        url: urlFail,
        headers,
        xml: xmlFail,
        timeout: 100,
      })).toThrow("EXPECTED ERROR");
  });
```

[Medium article about testing errors with jest](https://medium.com/@afolabiwaheed/how-to-test-a-function-thats-expected-to-throw-error-in-jest-2419cc7c6462)
