### ISSUE TITLE
Getting self signed certificate in certificate chain

### ISSUE THREAD

**Issue by hereisjai** [circa10a/easy-soap-request#45]
Hi using easy-soap-request connecting to a secured web services and i am getting the error  "self signed certificate in certificate chain".

I see the implementation of axios has a way of passing certificates bunde while making soap requests with custom agents like this.

var agent = new https.Agent({ 
  ca: fs.readFileSync('ca.pem') 
});

Has this also  been wrapped for the use in easy-soap-request, as i dont yet find an option of doing so.

**Comment by circa10a** [comment]
`easy-soap-request` has an `extraOpts` object parameter that will forward any additional keys/values on to axios like so:

```javascript
const agent = new https.Agent({
  ca: fs.readFileSync('ca.pem')
});

await soapRequest({ 
  url: url,
  headers: sampleHeaders,
  xml: xml,
  timeout: 1000,
  extraOpts: {
    httpsAgent: agent
  },
})
```
