### ISSUE TITLE
Add Type Definitions

### ISSUE THREAD

**Issue by lauchness** [circa10a/easy-soap-request#48]
As a developer I would like to have accurate type definitions.

Any chance this is on the road map for the project?

**Comment by circa10a** [comment]
I didn't have it planned, but a PR is more than welcome 🙂

**Comment by lauchness** [comment]
Fair enough, I'll put it on the personal backlog 🙂

**Comment by circa10a** [comment]
@lauchness https://www.npmjs.com/package/@types/easy-soap-request

**Comment by circa10a** [comment]
@lauchness good to close the issue?

**Comment by lauchness** [comment]
I would say so, though I haven't verified as I'm not using easy-soap-request anymore. It looks good to me.
