### ISSUE TITLE
Consistent error handling

### ISSUE THREAD

**Issue by luixal** [circa10a/easy-soap-request#50]
Hi,

Lately, I've been dealing with a SOAP service that works pretty badly (can't do anything about it, it's a third party service) but I had to make some changes in the lib so I could get error codes. In function (soapRequest)[], I've change this (at [line 61](https://github.com/circa10a/easy-soap-request/blob/25500b1eb239755fb6ea203f57c95af9a78d2a4b/index.js#L61)):

```js
}).catch((error) => {
    if (error.response) {
        reject(error.response.data);
    } else {
        reject(error);
    }
});
```
with a some quite identical to the one when resolving instead or rejecting:

```js
}).catch((error) => {
    if (error.response) {
        reject({
            response: {
                headers: error.response.headers,
                body: error.response.data,
                statusCode: error.response.status,
            }
        });
    } else {
        reject(error);
    }
});
```

I feel this quite necessary (I need the statusCode when something fails rather than when everything goes well) and more consistent (you get the same info if possible when something fails).

Would you like a PR for this or do you think current behaviour is the right one?

Thanks for your work!

**Comment by circa10a** [comment]
Sounds good to me! Just make sure to bump the package.json to version 5.0.0 so we don't break anyone

**Comment by circa10a** [comment]
Sounds good to me. Just be sure to bump the package.json version to 5.0.0 so we don't break anyone

**Comment by luixal** [comment]
Sorry I didn't got on this. I moved on to another task and haven't use this package since then :(
