### ISSUE TITLE
Type 'Uint8Array' is not assignable to type 'string'. Deno

### ISSUE THREAD

**Issue by rockXload** [circa10a/easy-soap-request#55]
![image](https://user-images.githubusercontent.com/97867790/154408650-09b91dc7-e0d0-4cbe-9410-1edb83b6cfe6.png)

**Comment by circa10a** [comment]
This is not a very informative issue. Assuming your variable `xml` is of the wrong type. Hard to know for sure given the lack of detail around the issue

**Comment by rockXload** [comment]
found the solution. as i need to decode the xml file using `new TextDecoder().decode(xml);`
