### ISSUE TITLE
Getting error while reading xml file

### ISSUE THREAD

**Issue by sahithya31** [circa10a/easy-soap-request#57]
Hi,
I'm trying to make a SOAP call using SOAP WSDL. I need to pass the username and password and click on submit, if the user is authenticate user it should fetch the details from the SOAP WSDL  I have created an XML file(SoapRequest.xml) in "scripts" folder but while reading file path( const xml = fs.readFileSync('./scripts/SoapRequest.xml', 'utf-8'); ) it is throwing an error "No such file or directory, open './scripts/SoapRequest.xml" Please help me with the issue.
Thanks in advance

**Comment by circa10a** [comment]
Your application is easily running in the wrong directory or that path simply does not exist. Either way, this issue is unrelated to the easy-soap-request library.
